### ISSUE TITLE
Truncation too aggressive

### ISSUE THREAD

**Issue by pjlsergeant** [hoytech/Unicode-Truncate#2]
Consider:

`perl -e 'use Unicode::Truncate; warn truncate_egc("01234567", 10);'`

String is less than 10 characters (and indeed bytes) but it still gets truncated to:

`0123456…`

Is that intentional?

**Comment by hoytech** [comment]
There was a reason, but it was an implementation detail. I agree, it makes more sense to leave the string alone if it will fit in the size. I've changed this in a1be42d3622c0d0c7ed2f1494b3e64a942a4ffc4 and have released 0.303 to CPAN.
